server:
  port: 8081
spring:
  devtools:
    restart:
      exclude: static/**
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
druid:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Zucking888
    min-idle: 1
    max-active: 20
    test-on-borrow: true
logging:
  level:
    tk.mybatis:TRACE
mybatis:
  type-aliases-package: com.zh.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers:
    - com.zh.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
