server:
  port: 8081
spring:
  devtools:
    restart:
      exclude: static/**
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Zucking888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5